/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Container.Content.Component;

import java.awt.BorderLayout;
import scrumpe.UI.AppStyle;
import scrumpe.UI.UIComponent;

/**
 *
 * @author MJ. Verhoeven
 */
public class ContentHeader extends UIComponent {

    String screenName;
    /**
     * Creates new form ContentHeader
     */
    public ContentHeader(String screenName) {
        super();
        initComponents();
        setBackground(AppStyle.TRANSLUCENT);
        setNavigation();
        screenTitle.setText(screenName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        screenTitle = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(AppStyle.TRANSLUCENT);

        screenTitle.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        screenTitle.setText("Home");
        screenTitle.setToolTipText("");
        jPanel1.add(screenTitle);

        add(jPanel1, java.awt.BorderLayout.LINE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel screenTitle;
    // End of variables declaration//GEN-END:variables

    public void applyCustomStyle() {
        setBackground(AppStyle.TRANSLUCENT);
    }

    private void setNavigation() {
        add(new Navigation(),BorderLayout.LINE_END);
    }

    @Override
    public void initCustomComponents() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
