/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Container.Content.Component;

import java.awt.FlowLayout;
import scrumpe.UI.MainUI;
import scrumpe.UI.UIComponent;

/**
 * content of the footer - Swing design file
 * @author MJ. Verhoeven
 */
public class FooterContent extends UIComponent {

    /**
     * Creates new form FooterContent
     */
    public FooterContent() {
//         super(new FlowLayout(FlowLayout.LEFT));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        jLabel1.setText("© Squerist 2016");
        add(jLabel1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    public void applyCustomStyle() {
    }

    @Override
    public void initCustomComponents() {
    }
}
