/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Container.Content.Component;

import java.awt.FlowLayout;
import java.util.List;
import java.util.ArrayList;
import javax.swing.JButton;
import scrumpe.UI.AppStyle;
import scrumpe.UI.UIComponent;

/**
 *  navigation component in header file
 * @author MJ. Verhoeven
 */
public class Navigation extends UIComponent {

    /**
     * Creates new form Navigation
     */
    List<JButton> navButtons = new ArrayList<>();
    private static Navigation instance;
    private static Class currentScreen;
    Navigation() {
        super();
        initComponents();
        setBackground(AppStyle.TRANSLUCENT);
        setNavigation();
    }

    /**
     *
     * @return
     */
    public static Navigation getInstance(){
        if(instance == null){
            instance = new Navigation();
        }
        return instance;
    }
    private void setNavigation(){
        this.removeAll();
        add(new JButton("Records"));
        add(new JButton("Help"));
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout();
        flowLayout1.setAlignOnBaseline(true);
        setLayout(flowLayout1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public void applyCustomStyle() {
        setBackground(AppStyle.TRANSLUCENT);
    }

    @Override
    public void initCustomComponents() {
    }
}
