/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Container.Content.Component;

import java.util.List;
import java.util.ArrayList;
import javax.swing.JButton;

/**
 *  navigation component in header file
 * @author MJ. Verhoeven
 */
public class Navigation extends javax.swing.JPanel {

    /**
     * Creates new form Navigation
     */
    List<JButton> navButtons = new ArrayList<>();
    private static Navigation instance;
    private static Class currentScreen;
    private Navigation() {
        initComponents();
    }

    /**
     *
     * @return
     */
    public static Navigation getInstance(){
        if(instance == null){
            instance = new Navigation();
        }
        return instance;
    }
    private void setNavigation(){
        this.removeAll();
        add(new JButton("Records"));
        add(new JButton("Help"));
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        jButton1.setText("jButton1");
        add(jButton1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
