/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Container.Content.Component;

import Container.MainContainer;
import Container.MainContainer.MainScreens;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import scrumpe.UI.MainUI;
import scrumpe.UI.UIComponent;
import scrumpe.UI.WrapLayout;

/**
 *
 * @author Max Verhoeven
 */
public class TempNavigation extends UIComponent implements ActionListener{

    /**
     * Creates new form TempNavigation
     */
    public TempNavigation() {
        initComponents();
        setLayout(new WrapLayout());
        for(Enum<MainScreens> screen : MainContainer.mainScreens.keySet()){
            JButton j = new JButton(screen.name());
            j.addActionListener(this);
            j.setActionCommand(screen.name());
            add(j);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void actionPerformed(ActionEvent e) {
        MainContainer.changeScreen(e.getActionCommand());
    }

    @Override
    public void initCustomComponents() {
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
