/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Container.Content;

import Container.MainContainer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.border.Border;
import javax.swing.border.EmptyBorder;
import scrumpe.UI.AppStyle;
import scrumpe.UI.MainUI;

/**
 * Creates new form LoginScreen 
 * @author MJ. Verhoeven
 */
public class LoginScreen extends MainUI implements ActionListener{
   private static final String LOGIN_ACTION="login",FORGOTPASS_ACTION="forgotPass";
    public LoginScreen() {
       super("Login Screen",false);
        initComponents();
        addListeners();
        Border margin = new EmptyBorder(10,10,10,10);
        setBorder(margin);
        setBackground(AppStyle.BG_COLOR_LIGHT);
        initCustomComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        passwordField = new javax.swing.JPasswordField();
        userNameField = new javax.swing.JTextField();
        loginBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        forgotPassBtn = new javax.swing.JButton();

        setAlignmentY(1.0F);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 2, 0, 2, 0, 2, 0, 2, 0};
        layout.rowHeights = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0};
        setLayout(layout);

        passwordField.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 4, 5, 4);
        add(passwordField, gridBagConstraints);

        userNameField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        userNameField.setText("Username");
        userNameField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 4, 5, 4);
        add(userNameField, gridBagConstraints);

        loginBtn.setText("Login");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 4, 5, 4);
        add(loginBtn, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("Welcome to Scrumpe!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 20, 20);
        add(jLabel2, gridBagConstraints);

        forgotPassBtn.setText("Forgot password?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        add(forgotPassBtn, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton forgotPassBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField userNameField;
    // End of variables declaration//GEN-END:variables
    @Override
    public void actionPerformed(ActionEvent e) {
        switch(e.getActionCommand()){
            case LOGIN_ACTION:
                doLogin();
                break;
            case FORGOTPASS_ACTION:
                goToForgotPass();
                break;
        }
    }

    private void addListeners() {
        loginBtn.addActionListener(this);
        loginBtn.setActionCommand(LOGIN_ACTION);
        forgotPassBtn.addActionListener(this);
        forgotPassBtn.setActionCommand(FORGOTPASS_ACTION);
    }

    private void doLogin() {
        MainContainer.changeScreen(MainContainer.MainScreens.Main);
    }

    private void goToForgotPass() {
    }


}
