
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Container.Content;

import Container.Content.Component.Admin.UserList;
import Container.Content.Component.ContentHeader;
import Container.Content.Component.Course;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ScrollPaneConstants;
import scrumpe.UI.AppStyle;
import scrumpe.UI.MainUI;
import scrumpe.UI.UIComponent;
import scrumpe.UI.WrapLayout;
/**
 * The mainscreen after the login page
 * @author MJ. Verhoeven
 */
public class MainScreen extends MainUI{

   

    List<Course> courses = new ArrayList<>(); 
    int courseCollumns = 4;
    public MainScreen() {
        super("Welcome !",true);
        initComponents();
        initCustomComponents();
    }
    
    @Override
    public void initCustomComponents() {
        jScrollPane1.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        addCourses();
        jScrollPane1.setViewportBorder(AppStyle.createPadding(0, 5, 0, 5));
        jScrollPane1.setBorder(AppStyle.createPadding());
        addAdminPanel();
        super.initCustomComponents(); //To change body of generated methods, choose Tools | Templates.
    }
    private void addCourses() {
        for (int i = 0; i < 40; i++) {
            Course c = new Course("Random course");
            courses.add(c);
        }
        courseContainer.setLayout(new WrapLayout());
        for(Course x:courses){
            x.setLayout(new WrapLayout());
            courseContainer.add(x);
            super.applyStyle(x);
        }
    }

    private void addAdminPanel() {
        GridBagConstraints gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weighty = 1.0;
        bodyContainer.add(new UserList(),gridBagConstraints);
    }

    public void applyCustomStyle() {
        descriptionContainer.setBorder(AppStyle.createThemeBorder(AppStyle.BorderPos.INSIDE));
        jLabel2.setOpaque(true);
        jLabel2.setBackground(Color.white);
        System.out.println(jLabel2.toString());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        bodyContainer = new javax.swing.JPanel();
        descriptionContainer = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        courseContainer = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        bodyContainer.setBackground(AppStyle.BG_COLOR_LIGHT);
        bodyContainer.setLayout(new java.awt.GridBagLayout());

        descriptionContainer.setLayout(new javax.swing.BoxLayout(descriptionContainer, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setText("Description Here");
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jLabel2.setName("test"); // NOI18N
        descriptionContainer.add(jLabel2);
        jLabel2.getAccessibleContext().setAccessibleDescription("");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        bodyContainer.add(descriptionContainer, gridBagConstraints);

        jScrollPane1.setBorder(null);

        courseContainer.setMinimumSize(new java.awt.Dimension(200, 10));
        jScrollPane1.setViewportView(courseContainer);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.8;
        bodyContainer.add(jScrollPane1, gridBagConstraints);

        add(bodyContainer, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyContainer;
    private javax.swing.JPanel courseContainer;
    private javax.swing.JPanel descriptionContainer;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

  


    
}
