/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Container.Content;

import Container.Content.Component.ContentHeader;
import scrumpe.UI.AppStyle;
import scrumpe.UI.UIComponent;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.UIManager;
import scrumpe.UI.MainUI;
/**
 *
 * @author Max Verhoeven
 */
public class RecordsScreen extends MainUI implements MouseListener {

    /**
     * Creates new form Records
     */
    public RecordsScreen() {
        super("Records",true);
        initComponents();
        initCustomComponents();
        
        for (int i = 0; i < 10; i++) {
              JPanel record = generateRecord("test", "12 sept", "13 sept", true);
        recordContainer.add(record);
        }
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        bodyContainer = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jPanelx = new javax.swing.JPanel();
        recordContainer = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        bodyContainer.setLayout(new java.awt.GridBagLayout());

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setText("jLabel2");
        jPanel4.add(jLabel2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 0.2;
        bodyContainer.add(jPanel4, gridBagConstraints);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        jScrollPane1.setMaximumSize(new java.awt.Dimension(720, 32767));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setMaximumSize(null);
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jToggleButton1.setText("Course ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.25;
        jPanel2.add(jToggleButton1, gridBagConstraints);

        jToggleButton2.setText("Date Started");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.25;
        jPanel2.add(jToggleButton2, gridBagConstraints);

        jToggleButton3.setText("Date Finished");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.25;
        jPanel2.add(jToggleButton3, gridBagConstraints);

        jToggleButton4.setText("Passed");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.25;
        jPanel2.add(jToggleButton4, gridBagConstraints);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanelx.setLayout(new java.awt.BorderLayout());

        recordContainer.setLayout(new javax.swing.BoxLayout(recordContainer, javax.swing.BoxLayout.Y_AXIS));
        jPanelx.add(recordContainer, java.awt.BorderLayout.PAGE_START);
        jPanelx.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanelx, java.awt.BorderLayout.CENTER);

        jScrollPane1.setViewportView(jPanel1);

        jPanel3.add(jScrollPane1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.8;
        bodyContainer.add(jPanel3, gridBagConstraints);

        add(bodyContainer, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyContainer;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelx;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JPanel recordContainer;
    // End of variables declaration//GEN-END:variables

    @Override
    public void initCustomComponents() {
        super.initCustomComponents(); //To change body of generated methods, choose Tools | Templates.
    }
    private JPanel generateRecord(String courseName,String dateStarted,String dateFinished,boolean didPass){
        GridBagConstraints  gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.weightx = 0.25;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 10, 0);
        JLabel course = new JLabel(courseName);
        JLabel dateS = new JLabel(dateStarted);
        JLabel dateF = new JLabel(dateFinished);
        JLabel didP = new JLabel(((didPass)?"Yes":"No"));
        JPanel jpanel = new JPanel(new GridBagLayout());
        jpanel.add(course,gridBagConstraints);
        jpanel.add(dateS,gridBagConstraints);
        jpanel.add(dateF,gridBagConstraints);
        jpanel.add(didP,gridBagConstraints);
        
        jpanel.addMouseListener(this);
        return jpanel;
    }

    @Override
    public void mouseClicked(MouseEvent e) {
        
    }

    @Override
    public void mousePressed(MouseEvent e) {
    }

    @Override
    public void mouseReleased(MouseEvent e) {
    }

    @Override
    public void mouseEntered(MouseEvent e) {
    }

    @Override
    public void mouseExited(MouseEvent e) {
    }
}
