/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Container.Content;

import Container.Content.Component.ContentHeader;
import Container.Content.Component.IContentHeader;
import java.awt.BorderLayout;
import scrumpe.UI.AppStyle;
import scrumpe.UI.UIComponent;

/**
 *
 * @author Max Verhoeven
 */
public class ResultsScreen extends UIComponent implements IContentHeader{

    /**
     * Creates new form ResultsScreen
     */
    public ResultsScreen() {
        initComponents();
        setBackground(AppStyle.TRANSLUCENT);
        addContentHeader();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodyContainer = new javax.swing.JPanel();
        descriptionContainer = new javax.swing.JPanel();
        description = new javax.swing.JLabel();
        courseContainer = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        bodyContainer.setBackground(AppStyle.BG_COLOR_LIGHT);
        bodyContainer.setLayout(new java.awt.BorderLayout());

        descriptionContainer.setMaximumSize(new java.awt.Dimension(500, 500));
        descriptionContainer.setMinimumSize(new java.awt.Dimension(500, 500));
        descriptionContainer.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 5));

        description.setText("jLable");
        descriptionContainer.add(description);

        bodyContainer.add(descriptionContainer, java.awt.BorderLayout.NORTH);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Question", "Correct Answer", "Your Answer", "Correct"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        courseContainer.add(jScrollPane2);

        bodyContainer.add(courseContainer, java.awt.BorderLayout.CENTER);

        add(bodyContainer, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyContainer;
    private javax.swing.JPanel courseContainer;
    private javax.swing.JLabel description;
    private javax.swing.JPanel descriptionContainer;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void applyCustomStyle() {
    }

    @Override
    public void addContentHeader() {
           add(new ContentHeader("Home"),BorderLayout.PAGE_START);
    }
}
